### PR TITLE
Update /dist files

### PR DESCRIPTION
**Pull request by TehNrd**
Re-ran build scripts to make sure these files are up to date. These files now use a more up to date version of jszip and have significant performance improvements.

### CODE REVIEW

**Comment by TehNrd** [comment]
Might also be worth making `master` the default branch on this repo. Currently it is gh-pages.

**Comment by calvinmetcalf** [comment]
gh-pages is the default so I don't have to keep the gh-pages branch uptodate

**Comment by TehNrd** [comment]
Ok, pretty sure these changes apply to that branch as well. I will check and submit a new PR if necessary.

**Comment by calvinmetcalf** [comment]
9054375824b1cd4f718ba6a820c982969591a9bf

**Pull request closed without merging**
